services:
  openconnect-proxy:
    build: .
    privileged: true  # Required for OpenConnect
    volumes:
      - ./tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf:ro
    ports:
      - "8224:8224"
    environment:
      VPN_SERVER: "VPN_SERVER_DNS_OR_IP"
      VPN_USERNAME: "VPN_USERNAME"
      VPN_PASSWORD: "VPN_PASSWORD"
    restart: unless-stopped